
package paz1c.knihy;

import java.awt.Frame;
import java.util.List;
import paz1c.knihy.DetailKnihyForm;

public class DetailKnihyForm extends javax.swing.JDialog {
    private Kniha kniha;
    private VydavatelstvoDao vydDao = DaoFactory.INSTANCE.getVydavatelstvoDao();
    private KategoriaDao katDao = DaoFactory.INSTANCE.getKategoriaDao();
      
    
    /*Nacita polozku kniha kt. bola vybrana a nastavi udaje do policok na obrazovke */
    
    public DetailKnihyForm(Kniha kniha, java.awt.Frame parent) {
        this(parent, true);
        this.kniha = kniha;
        
        Long id = kniha.getId();
        List<Vydavatelstvo> list = vydDao.vydavatelstvoPodlaId(id);
        Vydavatelstvo vyd = list.get(0);
        String vydavatelstvo = vyd.getNazov();
        
        List<Kategoria> listt = katDao.kategoriaPodlaId(id);
        Kategoria kat = listt.get(0);
        String kategoria = kat.getNazov();
        
        lblNazov.setText(kniha.getNazov());
        lblAutor.setText(kniha.getAutor());
        lblCena.setText(kniha.getCena().toString());
        txtAreaRecenzia.setText(kniha.getRecenzia());
        lblKategoria.setText(kategoria);
        lblVydavatelstvo.setText(vydavatelstvo);        
    }
    
    public DetailKnihyForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSlovoNazov = new javax.swing.JLabel();
        lblSlovoAutor = new javax.swing.JLabel();
        lblSlovoCena = new javax.swing.JLabel();
        lblNazov = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblCena = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRecenzia = new javax.swing.JTextArea();
        lblSlovoKategoria = new javax.swing.JLabel();
        lblSlovoVydavatelstvo = new javax.swing.JLabel();
        lblKategoria = new javax.swing.JLabel();
        lblVydavatelstvo = new javax.swing.JLabel();
        lblPozadie = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSlovoNazov.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSlovoNazov.setText("Nazov :");
        lblSlovoNazov.setFocusable(false);
        lblSlovoNazov.setInheritsPopupMenu(false);
        lblSlovoNazov.setRequestFocusEnabled(false);
        getContentPane().add(lblSlovoNazov, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 56, 22));

        lblSlovoAutor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSlovoAutor.setText("Autor :");
        lblSlovoAutor.setFocusable(false);
        lblSlovoAutor.setInheritsPopupMenu(false);
        lblSlovoAutor.setRequestFocusEnabled(false);
        getContentPane().add(lblSlovoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 56, 22));

        lblSlovoCena.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSlovoCena.setText("Cena:");
        lblSlovoCena.setFocusable(false);
        lblSlovoCena.setInheritsPopupMenu(false);
        lblSlovoCena.setRequestFocusEnabled(false);
        getContentPane().add(lblSlovoCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 56, 22));

        lblNazov.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNazov.setText("Nothing");
        lblNazov.setFocusable(false);
        lblNazov.setInheritsPopupMenu(false);
        lblNazov.setRequestFocusEnabled(false);
        getContentPane().add(lblNazov, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        lblAutor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblAutor.setText("John Smith");
        lblAutor.setFocusable(false);
        lblAutor.setInheritsPopupMenu(false);
        lblAutor.setRequestFocusEnabled(false);
        getContentPane().add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        lblCena.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCena.setText("00.00 € ");
        lblCena.setFocusable(false);
        lblCena.setInheritsPopupMenu(false);
        lblCena.setRequestFocusEnabled(false);
        getContentPane().add(lblCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 85, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtAreaRecenzia.setColumns(20);
        txtAreaRecenzia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtAreaRecenzia.setRows(5);
        txtAreaRecenzia.setFocusable(false);
        txtAreaRecenzia.setOpaque(false);
        txtAreaRecenzia.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txtAreaRecenzia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 200, 270));

        lblSlovoKategoria.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSlovoKategoria.setText("Kategoria:");
        lblSlovoKategoria.setFocusable(false);
        lblSlovoKategoria.setInheritsPopupMenu(false);
        lblSlovoKategoria.setRequestFocusEnabled(false);
        getContentPane().add(lblSlovoKategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        lblSlovoVydavatelstvo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSlovoVydavatelstvo.setText("Vydavatelstvo:");
        lblSlovoVydavatelstvo.setFocusable(false);
        lblSlovoVydavatelstvo.setInheritsPopupMenu(false);
        lblSlovoVydavatelstvo.setRequestFocusEnabled(false);
        getContentPane().add(lblSlovoVydavatelstvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblKategoria.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblKategoria.setText("kategoria");
        lblKategoria.setFocusable(false);
        lblKategoria.setInheritsPopupMenu(false);
        lblKategoria.setRequestFocusEnabled(false);
        getContentPane().add(lblKategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 80, -1));

        lblVydavatelstvo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblVydavatelstvo.setText("vydavatelstvo");
        lblVydavatelstvo.setFocusable(false);
        lblVydavatelstvo.setInheritsPopupMenu(false);
        lblVydavatelstvo.setRequestFocusEnabled(false);
        getContentPane().add(lblVydavatelstvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 107, -1));

        lblPozadie.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPozadie.setIcon(new javax.swing.ImageIcon("D:\\Skola\\PAZ_PROJEKT\\projekt\\book-background-image_mensie.jpg")); // NOI18N
        getContentPane().add(lblPozadie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailKnihyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailKnihyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailKnihyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailKnihyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                DetailKnihyForm dialog = new DetailKnihyForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblKategoria;
    private javax.swing.JLabel lblNazov;
    private javax.swing.JLabel lblPozadie;
    private javax.swing.JLabel lblSlovoAutor;
    private javax.swing.JLabel lblSlovoCena;
    private javax.swing.JLabel lblSlovoKategoria;
    private javax.swing.JLabel lblSlovoNazov;
    private javax.swing.JLabel lblSlovoVydavatelstvo;
    private javax.swing.JLabel lblVydavatelstvo;
    private javax.swing.JTextArea txtAreaRecenzia;
    // End of variables declaration//GEN-END:variables
}
