
package paz1c.knihy;


import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;
import paz1c.knihy.UpravitKnihaForm;

public class HlavnyFormularZakaznik extends javax.swing.JFrame {
    
    /*Definovanie privatnych premenych*/
private KnihaDao knihaDao 
            = DaoFactory.INSTANCE.getKnihaDao();

    private KnihaTableModel knihaTableModel = new KnihaTableModel();
            
    private boolean vytvorenyKosik = false;
    private Kniha vybrataKniha;
    private NakupnyKosikForm nakupnyKosikForm;
    
    private TableRowSorter knihaRowSorter = new TableRowSorter(knihaTableModel);
    
    private KnihaPodlaAutoraRowFilter knihaPodlaAutoraRowFilter 
            = new KnihaPodlaAutoraRowFilter();
    
    private KnihaPodlaNazvuRowFilter knihaPodlaNazvuRowFilter 
            = new KnihaPodlaNazvuRowFilter();
    /*
      Vytvorenie noveho hlavneho formulara HlavnyFormular
     */
    public HlavnyFormularZakaznik() {
        initComponents();
        
        
        /*Pri vytvoreni noveho formulara sa automaticky nacitaju vsetky knihy z databazy do tabulky */
        
        tabKniha.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                tabKnihaSelectionValueChanged(e);
            }
        });
        
        aktualizujZoznamKnih();        
    }
    /*Metoda kt. zariadi aby pokial v tabulke nie je vybrata 
    ziadna kniha nesli pouzivat tlacidla Uprav,Odstran,Detail */
    
     private void tabKnihaSelectionValueChanged(ListSelectionEvent e) {
        if(!e.getValueIsAdjusting()) {
            if(!tabKniha.getSelectionModel().isSelectionEmpty()) {
                
                btnDetail.setEnabled(true);
            } else {
                
                btnDetail.setEnabled(false);
            }
        }
    }

     /*Metoda kt. aktualizuje zoznam knih v tabulke*/
    private void aktualizujPodlaNazvu(String nazov){
        knihaTableModel.dajNazov(nazov);
    }
     
    private void aktualizujPodlaAutora(String autor){
        knihaTableModel.dajAutora(autor);
    }
     private void aktualizujZoznamKnih() {
        knihaTableModel.obnov();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        jNazov = new javax.swing.JLabel();
        txtVyhladavanie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabKniha = new javax.swing.JTable();
        btnNazvu = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnPodlaAutora = new javax.swing.JButton();
        btnKosik = new javax.swing.JButton();
        jPozadie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        jNazov.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jNazov.setText("KNIHY.SHOP");
        getContentPane().add(jNazov, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 320, 30));

        txtVyhladavanie.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtVyhladavanie.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtVyhladavanie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, -1));

        tabKniha.setModel(knihaTableModel);
        tabKniha.setRowSorter(knihaRowSorter);
        tabKniha.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabKniha.addMouseListener(new java.awt.event.MouseAdapter() {

        });
        jScrollPane1.setViewportView(tabKniha);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 130));

        btnNazvu.setText("Nazvu");
        btnNazvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazvuActionPerformed(evt);
            }
        });
        getContentPane().add(btnNazvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        btnDetail.setText("Detail");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        btnPodlaAutora.setText("Autora");
        btnPodlaAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPodlaAutoraActionPerformed(evt);
            }
        });
        getContentPane().add(btnPodlaAutora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 20));

        btnKosik.setText("Pridaj do kosika");
        btnKosik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosikActionPerformed(evt);
            }
        });
        getContentPane().add(btnKosik, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 250, 150, -1));

        jPozadie.setIcon(new javax.swing.ImageIcon("D:\\Skola\\PAZ_PROJEKT\\Books-Wallpaper-021.jpg")); // NOI18N
        getContentPane().add(jPozadie, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 470, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        int vybranyRiadok = tabKniha.getSelectedRow();
        int vybratyIndexVModeli = tabKniha.convertRowIndexToModel(vybranyRiadok);
        
        Kniha vybrataKniha
                = knihaTableModel.dajPodlaCislaRiadku(vybratyIndexVModeli);
        
        DetailKnihyForm detailKnihyForm 
                = new DetailKnihyForm(vybrataKniha, this);
        detailKnihyForm.setVisible(true);
        
        aktualizujZoznamKnih();
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnNazvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazvuActionPerformed
        String filter = txtVyhladavanie.getText();
        knihaPodlaNazvuRowFilter.setNazov(filter);
        
        aktualizujPodlaNazvu(filter);
        
        
    }//GEN-LAST:event_btnNazvuActionPerformed

    private void btnPodlaAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPodlaAutoraActionPerformed
        String filter = txtVyhladavanie.getText();
        knihaPodlaAutoraRowFilter.setAutor(filter);
        
        aktualizujPodlaAutora(filter);
    }//GEN-LAST:event_btnPodlaAutoraActionPerformed

    private void btnKosikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosikActionPerformed
        int vybranyRiadok = tabKniha.getSelectedRow();
        if(vybranyRiadok < 0){
            JOptionPane.showMessageDialog(this, "Nie je vybrata ziadna kniha !");
            return;
        }
        int vybratyIndexVModeli = tabKniha.convertRowIndexToModel(vybranyRiadok);
        
        vybrataKniha
                = knihaTableModel.dajPodlaCislaRiadku(vybratyIndexVModeli);
       
        if(vytvorenyKosik == false){
            nakupnyKosikForm = new NakupnyKosikForm(vybrataKniha, this);
            nakupnyKosikForm.setVisible(true);
            vytvorenyKosik = true;
        } else {
            nakupnyKosikForm.pridajVybratuKnihu(vybrataKniha);
            nakupnyKosikForm.setVisible(true);
        }
    }//GEN-LAST:event_btnKosikActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavnyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavnyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavnyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavnyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavnyFormular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnKosik;
    private javax.swing.JButton btnNazvu;
    private javax.swing.JButton btnPodlaAutora;
    private javax.swing.JLabel jLogo;
    private javax.swing.JLabel jNazov;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPozadie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabKniha;
    private javax.swing.JTextField txtVyhladavanie;
    // End of variables declaration//GEN-END:variables
}
