
package paz1c.knihy;

import java.awt.Frame;
import java.time.Clock;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;
import sun.util.calendar.CalendarUtils;

public class NakupnyKosikForm extends javax.swing.JFrame {

  private KnihaDao knihaDao = DaoFactory.INSTANCE.getKnihaDao();
  
  private KnihaTableModel knihaTableModel = new KnihaTableModel();
  private TableRowSorter knihaRowSorter = new TableRowSorter(knihaTableModel);
  
  private Kniha kniha;
  
  private List<Kniha> zoznamKnih = new ArrayList<Kniha>();
  
  
    public NakupnyKosikForm(Kniha kniha,javax.swing.JDialog parent ) {
        initComponents();
        
         tabZoznam.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                tabZoznamSelectionValueChanged(e);
            }
        });
         if(kniha != null){
             zoznamKnih.add(kniha);
         }
         
        aktualizujZoznamKnihVKosiku();  
    }
    
    public NakupnyKosikForm(Kniha kniha,javax.swing.JFrame parent ) {
        initComponents();
        
         tabZoznam.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                tabZoznamSelectionValueChanged(e);
            }
        });
         if(kniha != null){
             zoznamKnih.add(kniha);
         }
         
        aktualizujZoznamKnihVKosiku();  
    }

    private NakupnyKosikForm() {
        initComponents();
    }
    
    public void pridajVybratuKnihu(Kniha kniha){
        zoznamKnih.add(kniha);
        aktualizujZoznamKnihVKosiku();
    }
    
    private void tabZoznamSelectionValueChanged(ListSelectionEvent e) {
        if(!e.getValueIsAdjusting()) {
            if(!tabZoznam.getSelectionModel().isSelectionEmpty()) {
                btnOdstran.setEnabled(true);
            } else {
                btnOdstran.setEnabled(false);
            }
        }
    }

    private void aktualizujZoznamKnihVKosiku() {
        
        if(zoznamKnih != null){
            for(int i = 0; i<zoznamKnih.size(); i++){
                kniha=zoznamKnih.get(i);
                knihaTableModel.dajKnihuSTymtoIdDoKosika(kniha.getId(), zoznamKnih);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblKosik = new javax.swing.JLabel();
        btnKupit = new javax.swing.JButton();
        btnOdstran = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabZoznam = new javax.swing.JTable();
        btnStorno = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblPozadie = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKosik.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        lblKosik.setText("Nakupny kosik");
        getContentPane().add(lblKosik, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 220, 50));

        btnKupit.setText("Kupit");
        btnKupit.setFocusPainted(false);
        btnKupit.setFocusable(false);
        btnKupit.setOpaque(false);
        btnKupit.setRequestFocusEnabled(false);
        btnKupit.setRolloverEnabled(false);
        btnKupit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupitActionPerformed(evt);
            }
        });
        getContentPane().add(btnKupit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 78, -1));

        btnOdstran.setText("Odstran");
        btnOdstran.setFocusPainted(false);
        btnOdstran.setFocusable(false);
        btnOdstran.setOpaque(false);
        btnOdstran.setRequestFocusEnabled(false);
        btnOdstran.setRolloverEnabled(false);
        btnOdstran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdstranActionPerformed(evt);
            }
        });
        getContentPane().add(btnOdstran, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        tabZoznam.setModel(knihaTableModel);
        tabZoznam.setRowSorter(knihaRowSorter);
        tabZoznam.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabZoznam.addMouseListener(new java.awt.event.MouseAdapter() {

        });
        jScrollPane1.setViewportView(tabZoznam);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 430, 186));

        btnStorno.setText("Storno");
        btnStorno.setFocusable(false);
        btnStorno.setOpaque(false);
        btnStorno.setRequestFocusEnabled(false);
        btnStorno.setRolloverEnabled(false);
        btnStorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStornoActionPerformed(evt);
            }
        });
        getContentPane().add(btnStorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon("D:\\Skola\\PAZ_PROJEKT\\download (1).jpg")); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 70, 53));

        lblPozadie.setIcon(new javax.swing.ImageIcon("D:\\Skola\\PAZ_PROJEKT\\projekt\\Books-Background-1-625x416.jpg")); // NOI18N
        lblPozadie.setText("jLabel2");
        getContentPane().add(lblPozadie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 560, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdstranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdstranActionPerformed
        int vybranyRiadok = tabZoznam.getSelectedRow();
        int vybratyIndexVModeli = tabZoznam.convertRowIndexToModel(vybranyRiadok);
        
        Kniha vybrataKniha
                = knihaTableModel.dajPodlaCislaRiadku(vybratyIndexVModeli);

        if(vybrataKniha == null) {
            return;
        } else {
            for(int i=0; i<zoznamKnih.size(); i++){
                Long idKnihy = zoznamKnih.get(i).getId();
                if(vybrataKniha.getId()==idKnihy){
                    zoznamKnih.remove(i);
                }
            }
        }
        aktualizujZoznamKnihVKosiku();       
    }//GEN-LAST:event_btnOdstranActionPerformed

    private void btnKupitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupitActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(this, "Dakujeme za vas nakup");
      
    }//GEN-LAST:event_btnKupitActionPerformed

    private void btnStornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStornoActionPerformed
       
        dispose();
    }//GEN-LAST:event_btnStornoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NakupnyKosikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NakupnyKosikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NakupnyKosikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NakupnyKosikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NakupnyKosikForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKupit;
    private javax.swing.JButton btnOdstran;
    private javax.swing.JButton btnStorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKosik;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPozadie;
    private javax.swing.JTable tabZoznam;
    // End of variables declaration//GEN-END:variables
}
