
package paz1c.knihy;

import java.awt.Frame;
import java.math.BigDecimal;

public class UpravitKnihaForm extends javax.swing.JDialog {
    private KnihaDao knihaDao 
            = DaoFactory.INSTANCE.getKnihaDao();
    
    private Kniha kniha;
    
    public UpravitKnihaForm(Frame parent) {
        this(new Kniha(), parent);
    }
    
    
    public UpravitKnihaForm(Kniha kniha, Frame parent) {
        this(parent, true);
        
        this.kniha = kniha;
       txtNazov.setText(kniha.getNazov());
        txtAutor.setText(kniha.getAutor());
        if(kniha.getCena() == null) {
            txtCena.setText("0");
        } else {
            txtCena.setText(kniha.getCena().toString());
        }
        if(kniha.getKategoria_id() == null){
            txtKategoria.setText("neznama");
        } else {
            txtKategoria.setText(kniha.getKategoria_id().toString());
        }
        if(kniha.getVydavatelstvo_id() == null) {
            txtVydavatelstvo.setText("nezname");
        } else {
            txtVydavatelstvo.setText(kniha.getVydavatelstvo_id().toString());
        }
    }
    
    /**
     * Creates new form UpravitTeplakyForm
     */
    private UpravitKnihaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }



    



   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazov = new javax.swing.JLabel();
        txtNazov = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblCena = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        btnStorno = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        lblPopis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPopis = new javax.swing.JTextArea();
        lblLogo = new javax.swing.JLabel();
        lblMoto = new javax.swing.JLabel();
        lblKategoria = new javax.swing.JLabel();
        lblVydavatelstvo = new javax.swing.JLabel();
        txtKategoria = new javax.swing.JTextField();
        txtVydavatelstvo = new javax.swing.JTextField();
        lblPozadie = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNazov.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNazov.setText("Nazov :");
        getContentPane().add(lblNazov, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 89, 23));
        getContentPane().add(txtNazov, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 61, 295, -1));

        lblAutor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblAutor.setText("Autor:");
        getContentPane().add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 70, -1));
        getContentPane().add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 101, 295, -1));

        lblCena.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCena.setText("Cena :");
        getContentPane().add(lblCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, 70, -1));
        getContentPane().add(txtCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 141, 295, -1));

        btnStorno.setText("Storno");
        btnStorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStornoActionPerformed(evt);
            }
        });
        getContentPane().add(btnStorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 365, -1, -1));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 365, -1, -1));

        lblPopis.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPopis.setText("Popis :");
        getContentPane().add(lblPopis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, 70, -1));

        txtAreaPopis.setColumns(20);
        txtAreaPopis.setRows(5);
        jScrollPane1.setViewportView(txtAreaPopis);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 179, 295, 81));
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 53, 27));

        lblMoto.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        lblMoto.setIcon(new javax.swing.ImageIcon("D:\\Skola\\PAZ_PROJEKT\\logoBook-paz1c.gif")); // NOI18N
        lblMoto.setText("KNIHY.SHOP  ");
        getContentPane().add(lblMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 0, 347, -1));

        lblKategoria.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblKategoria.setText("Kategoria :");
        getContentPane().add(lblKategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 285, 89, -1));

        lblVydavatelstvo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblVydavatelstvo.setText("Vydavatelstvo :");
        getContentPane().add(lblVydavatelstvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 329, 118, -1));
        getContentPane().add(txtKategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 287, 295, -1));
        getContentPane().add(txtVydavatelstvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 331, 295, -1));

        lblPozadie.setIcon(new javax.swing.ImageIcon("D:\\Skola\\PAZ_PROJEKT\\projekt\\book-background-image.jpg")); // NOI18N
        lblPozadie.setText("jLabel1");
        getContentPane().add(lblPozadie, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 550, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        kniha.setNazov(txtNazov.getText());
        kniha.setAutor(txtAutor.getText());
        kniha.setCena(new BigDecimal(txtCena.getText()));
        kniha.setRecenzia(txtAreaPopis.getText());
        kniha.setKategoria_id(new Long(txtKategoria.getText()));
        kniha.setVydavatelstvo_id(new Long(txtVydavatelstvo.getText()));
        
        knihaDao.save(kniha);
        
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnStornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStornoActionPerformed
         dispose();
    }//GEN-LAST:event_btnStornoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpravitKnihaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpravitKnihaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpravitKnihaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpravitKnihaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                UpravitKnihaForm dialog = new UpravitKnihaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnStorno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblKategoria;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMoto;
    private javax.swing.JLabel lblNazov;
    private javax.swing.JLabel lblPopis;
    private javax.swing.JLabel lblPozadie;
    private javax.swing.JLabel lblVydavatelstvo;
    private javax.swing.JTextArea txtAreaPopis;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtKategoria;
    private javax.swing.JTextField txtNazov;
    private javax.swing.JTextField txtVydavatelstvo;
    // End of variables declaration//GEN-END:variables
}
